### ISSUE TITLE
Add: A basic ticket system

### ISSUE THREAD

**Issue by zephiowl** [Zephira58/purplewood#6]
Add a small ticket system which happens when a user runs the /ticket <value> command. Allowing a user to specify a ticket channel to be created. IE "zephira-discordiscool" or so

The ticket response body should be private, ie only the user can see it. Staff should have access, the creator of the ticket and nobody else. And it should notify/ping staff role positions as found in the config file.

**Comment by Zephira58** [comment]
Decided its not mandatory
